application: live-music-archive
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /artists
  script: artists.app

- url: /task/scrape/artist/
  script: scrape_artists.app
  login: admin

libraries:
- name: django
  version: "1.2"

builtins:
- deferred: on
