application: live-music-archive
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /task/.*
  script: tasks.app
  login: admin

- url: /_ah/spi/.*
  script: services.application

builtins:
- deferred: on
- remote_api: on
